### ISSUE TITLE
v3.11.0 - formatters no longer seem to be added by default

### ISSUE THREAD

**Issue by zoojar** [dylanratcliffe/onceover#201]
since v3.11.0, running `onceover run spec` without supplying the --format parameter causes the following error:

```
WARN -> The 'type' key for mocked functions is deprecated and will be ignored, please remove it.
DEBUG -> Evaluating template testconfig_Rakefile.erb
DEBUG -> Reading /app/environment.conf
DEBUG -> Evaluating template spec_helper.rb.erb

Error while running: #<NoMethodError: undefined method `each' for nil:NilClass>
(erb):45:in `write_spec_helper'
/usr/local/lib/ruby/2.4.0/erb.rb:896:in `eval'
/usr/local/lib/ruby/2.4.0/erb.rb:896:in `result'
/usr/local/bundle/gems/onceover-3.11.0/lib/onceover/controlrepo.rb:563:in `evaluate_template'
/usr/local/bundle/gems/onceover-3.11.0/lib/onceover/testconfig.rb:226:in `write_spec_helper'
/usr/local/bundle/gems/onceover-3.11.0/lib/onceover/runner.rb:34:in `prepare!'
/usr/local/bundle/gems/onceover-3.11.0/lib/onceover/cli/run.rb:50:in `block (2 levels) in command'
/usr/local/bundle/gems/cri-2.6.1/lib/cri/command.rb:298:in `run_this'
/usr/local/bundle/gems/cri-2.6.1/lib/cri/command.rb:251:in `run'
/usr/local/bundle/gems/cri-2.6.1/lib/cri/command.rb:264:in `run'
/usr/local/bundle/gems/cri-2.6.1/lib/cri/command.rb:264:in `run'
/usr/local/bundle/gems/onceover-3.11.0/bin/onceover:7:in `<top (required)>'
/usr/local/bundle/bin/onceover:17:in `load'
/usr/local/bundle/bin/onceover:17:in `<top (required)>'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:74:in `load'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:27:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli.rb:335:in `exec'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli.rb:20:in `dispatch'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli.rb:11:in `start'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/exe/bundle:32:in `block in <top (required)>'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/exe/bundle:24:in `<top (required)>'
/usr/local/bin/bundle:22:in `load'
/usr/local/bin/bundle:22:in `<main>'

```

fixed this by adding format config to onceover.yaml:
```
opts:
  :format:
    - 'documentation'
```

could be an issue/bug?

**Comment by dylanratcliffe** [comment]
@zoojar Are you still seeing this with the latest version?

**Comment by cyberkov** [comment]
I can confirm that i ran into this issue on 3.14.1 as well. When adding `--format documentation` it works.
