### ISSUE TITLE
groups should be able to be empty

### ISSUE THREAD

**Issue by jessereynolds** [dylanratcliffe/onceover#55]
It seems that onceover doesn't like empty groups of anything. It'd be pretty nice if it could handle empty groups. 

```
jesse@So-Much-For-Subtlety control-repo $ be onceover run spec  --trace

Error while running: #<NoMethodError: undefined method `each' for nil:NilClass>
/Users/jesse/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/onceover-3.0.7/lib/onceover/group.rb:30:in `initialize'
/Users/jesse/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/onceover-3.0.7/lib/onceover/testconfig.rb:52:in `new'
/Users/jesse/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/onceover-3.0.7/lib/onceover/testconfig.rb:52:in `block in initialize'
/Users/jesse/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/onceover-3.0.7/lib/onceover/testconfig.rb:52:in `each'
/Users/jesse/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/onceover-3.0.7/lib/onceover/testconfig.rb:52:in `initialize'
/Users/jesse/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/onceover-3.0.7/lib/onceover/cli/run.rb:41:in `new'
/Users/jesse/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/onceover-3.0.7/lib/onceover/cli/run.rb:41:in `block (2 levels) in command'
/Users/jesse/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cri-2.6.1/lib/cri/command.rb:298:in `run_this'
/Users/jesse/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cri-2.6.1/lib/cri/command.rb:251:in `run'
/Users/jesse/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cri-2.6.1/lib/cri/command.rb:264:in `run'
/Users/jesse/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cri-2.6.1/lib/cri/command.rb:264:in `run'
/Users/jesse/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/onceover-3.0.7/bin/onceover:7:in `<top (required)>'
/Users/jesse/.rbenv/versions/2.3.0/bin/onceover:23:in `load'
/Users/jesse/.rbenv/versions/2.3.0/bin/onceover:23:in `<main>'
```

**Comment by jessereynolds** [comment]
I have a fix for this working here, I'll make a PR "soon".

**Comment by dylanratcliffe** [comment]
Merged
